extends: [[spectral:oas, off]]
rules:
# OWASP01:BROKEN OBJECT LEVEL AUTHORIZATION
  OWASP01-oas3-path-security-multi-level:
    description: Check operation security is defined
    severity: "error"
    given: "$.paths.*.*"
    then:
      field: 'security'
      function: truthy
# OWASP02:BROKEN AUTHENTICATION
  oas3-api-security-defined:
    description: Check API security is defined at top level
    severity: "error"
    given: "$"
    then:
      field: 'security'
      function: truthy

  oas3-operation-security-defined:
    description: Check operation security is defined
    severity: "error"
    given: "$.paths.*.*"
    then:
      field: 'security'
      function: truthy

  oas3-operation-security-scopes-defined:
    description: Check operation security's bearer_auth is defined
    severity: "error"
    given: "$.paths[*][*]..security.*"
    then:
      field: 'bearer_auth'
      function: truthy