openapi: "3.0.0"
info:
  version: 1.0.0 # allow versioning on the API specification(this file)
  title: OpenAPI specification for Order 
servers:
  - url: http://localhost.swagger.io/v1
paths:
  /companies:
    get:
      operationId: listCompanies
      parameters:
        - name: limit # result pagination
          in: query # can be also passed in header
          schema:
            type: integer
      responses:
        default:
          description: returned
          content:
            application/json:
              schema:
                type: object     
  /companies/{companyId}:
    get:
      operationId: showCompanyById
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: returned
          content:
            application/json:
              schema:
                type: object
  /companies/{companyId}/orders:
    get:
      operationId: showOrdersByCompanyId
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: returned
          content:
            application/json:
              schema:
                type: object
    post:
      operationId: createOrderInCompanyId
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
      requestBody: 
        description: create order
        content:
          application/json:
            schema:
              type: object
      responses:
        default:
          description: returned
          content:
            application/json:
              schema:
                type: object             
  /companies/{companyId}/orders/{orderId}:
    get:
      operationId: showOrderByCompanyId
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
        - name: orderId
          in: path
          required: true
          schema:
            type: string            
      responses:
        default:
          description: returned
          content:
            application/json:
              schema:
                type: object    
    delete:
      operationId: deleteOrderByCompanyId
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
        - name: orderId
          in: path
          required: true
          schema:
            type: string            
      responses:
        default:
          description: returned
          content:
            application/json:
              schema:
                type: object                        
  /companies/{companyId}/schemalessObject:
    get:
      operationId: listSchemalessObjectsByCompanyId
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: returned
          content:
            application/json:
              schema:
                type: object
    post:
      operationId: createObjectInCompanyId
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
      requestBody: 
        description: create object
        content:
          application/json:
            schema:
              type: object
      responses:
        default:
          description: returned
          content:
            application/json:
              schema:
                type: object              
  /admin/executeSql:
    patch:
      operationId: adminPost
      requestBody: 
        description: create order
        content:
          '*/*':
            schema:
              type: string # malicious command can be injected to produce unexpected results
      responses:
        default:
          description: returned
          content:
            application/json:
              schema:
                type: object                